### ISSUE TITLE
Fix interface blocked during combat for character status screen

### ISSUE THREAD

**Issue by aaronma37** [Zarant/WoW_Hardcore#167]

**Comment by Dirtimoney** [comment]
-- CharacterStatusScreen.Lua seems to be the culprit.
-- Commenting our line "PanelTemplates_SetNumTabs(CharacterFrame, TabID)" resolves the issue of not being able to open in combat.
-- The interface still throws an "Interface action Failed because of Addon" when the player clicks the "HC" tab, but the information is still display.

**Comment by aaronma37** [comment]
This might work for inspect but not character frame because inspect is technically a widget, and you can really do anything in it like you could with the char frame like move things around.

**Comment by aaronma37** [comment]
Regarding the ui issues, there were occassions where switching to the hc tab wouldn't close the others leaving artifacts. To test, try switching to and from the hc tab to other tabs

**Comment by Dirtimoney** [comment]
> This might work for inspect but not character frame because inspect is technically a widget, and you can really do anything in it like you could with the char frame like move things around.

This is currently working for the inspect frame and the character frame.

**Comment by Dirtimoney** [comment]
> Regarding the ui issues, there were occassions where switching to the hc tab wouldn't close the others leaving artifacts. To test, try switching to and from the hc tab to other tabs

Tested by flipping between tabs on my character and an inspected character. No artifacts left behind

**Comment by aaronma37** [comment]
Thats great!

**Comment by aaronma37** [comment]
removed that line and merged

**Comment by aaronma37** [comment]
In the WotLK client, an additional interface action blocked message occurs when in combat + hitting the HC tab.  We can optionally disable the hc tab during combat to alleviate this
