### ISSUE TITLE
Investigate minimap disappearing/force init settings values

### ISSUE THREAD

**Issue by aaronma37** [Zarant/WoW_Hardcore#170]

**Comment by Dirtimoney** [comment]
What does this issue deal with? Is it the scale being set below 0 and shutting off the addon?

**Comment by aaronma37** [comment]
Some hardcore settings dont get properly initialized when upgrading the addon. Particularly scale, alert pos x and y. That makes part of the options screen disappear. In some cases it seems like the minimap icon info can get corrupted too. Fix would be to make sure hardcore settings are in correct bounds upon startup

**Comment by aaronma37** [comment]
Couldn't replicate missing minimap button, but fixed half of menu options not showing

**Comment by Dirtimoney** [comment]
> Couldn't replicate missing minimap button, but fixed half of menu options not showing

If you drop your scale in the options pane to 0 the minimap button should disaappear and make the HC addon break if you do a reload ui, so if they are /console scripterrors 0, the UI warnging will disappear for them and the minimap but will stay. But when you do a reload ui the minimap button is gone and HC show brings up the options pane however the minimap button does not return the button and the addon is no longer tracking progress

**Comment by aaronma37** [comment]
There is that but there is also an issue where players are experiencing similar symptoms without touching the scale.

**Comment by Dirtimoney** [comment]
Was this also resolved with the new update? I thought it was being work in-tandem with the Character screen not opening in combat, could be mistaken.

**Comment by aaronma37** [comment]
I think so, j just want to leave it around for a bit to see if we get any more reports of it
