### ISSUE TITLE
NoHealthPotions

### ISSUE THREAD

**Issue by Dirtimoney** [Zarant/WoW_Hardcore#187]
This achievement leaves out about 25 other potions and flasks that gain health. Not sure if we want to update it since there was no HC TBC (i dont think) all those items are missed and the new ones in WoTLK. Not sure if that is intended, but possible given the name.

**Comment by aaronma37** [comment]
good call! We should keep in mind that we need to do localization changes sometime soon

**Comment by Dirtimoney** [comment]
> good call! We should keep in mind that we need to do localization changes sometime soon

You keep saying localization changes and im not sure i know what that means, and im getting to the point of being too afraid to ask rofl

**Comment by aaronma37** [comment]
Fr.classic.wowhead.com/item=6469
Vs
Classic.wowhead.com/item=6469

**Comment by aaronma37** [comment]
You could always do item ids too, but things are harder to keep track of across clients

**Comment by Dirtimoney** [comment]
> You could always do item ids too, but things are harder to keep track of across clients

I was just going to say that, at least the itemId is the same lol the only thing i could think of is do a local database file inside the addon package that we call for it, since there are so few items to track for that one. But there is probably a way to track when someone gains health from an item, and then we just check for the exceptions listed in the achievement

**Comment by Knics** [comment]
sorry for the late comment, just noticed this. Not really an issue. The achievement specifically states "items with Health Potion in the name are not allowed to be used, Items that restore health which are not Healing Potions (e.g. Healthstones or Crystal Restore) can be used."  This covers all other potions or flasks that restore health.

**Comment by Dirtimoney** [comment]
> sorry for the late comment, just noticed this. Not really an issue. The achievement specifically states "items with Health Potion in the name are not allowed to be used, Items that restore health which are not Healing Potions (e.g. Healthstones or Crystal Restore) can be used." This covers all other potions or flasks that restore health.

Copy, just thought that since they listed the Hearthstone's (a conjured item) and Crystal Restore(an item without Health potion in the name but restored HP) but did not specify that any other potion was still still allowed. So it seems that if you are doing this achievement and are alchemy its kind of a moot challenge.

**Comment by aaronma37** [comment]
Oh nice! Well good thing we didnt start this one yet.
