### ISSUE TITLE
Version Check for Achievements

### ISSUE THREAD

**Issue by Dirtimoney** [Zarant/WoW_Hardcore#188]
-- Setup a way for the achievements to show or not show based on the Version of the client the player is running

**Comment by aaronma37** [comment]
By version of the client, do you mean WotLK vs Era vs SoM?  We already have that; some achievements are cut from wotlk

**Comment by Dirtimoney** [comment]
> By version of the client, do you mean WotLK vs Era vs SoM? We already have that; some achievements are cut from wotlk

I did, because some achievements just says not available for wotlk, instead of removing them as an option. Were they left and marked as unachievable so people would not ask why they were not there?

Also could do modified versions of the unavailable ones like staying on the continet for the home bound one until 60? Just some ideas.

**Comment by aaronma37** [comment]
I see, we can add that then
