### ISSUE TITLE
NoHealthPotions Fails on making a Health Potion

### ISSUE THREAD

**Issue by Dirtimoney** [Zarant/WoW_Hardcore#222]
So this is failing due to the interaction of UNIT_SPELLCAST_SUCCEEDED, When crafting an item this is the event that is fired, failing anyone making a health potion without ever using it.

**Comment by Dirtimoney** [comment]
After doing some checking using a potion that gave health but wasnt a health potion, we will probably want to use a combination of checking for the following events: 
UNIT_SPELLCAST_SENT: unit, target, castGUID, spellID
UNIT_COMBAT: unitTarget, event, flagText, amount, schoolMask
UNIT_SPELLCAST_SUCCEEDED: unitTarget, castGUID, spellID

When using a potion, those are the three that fire in that order, when crafting a potion you then have the UNIT_SPELLCAST_CHANNEL_START right after the sent, and then you have the UNIT_SPELLCAST_CHANNEL_STOP right after the succeeded. So since the drinking of the potion doesnt use the item name but there. I will need to make a toon to see how a heal spell event spits out data (like what fields it populates) i assume all them, because the potion doesnt have a target so thats nil and I am thinking of checking for that and checking for a UNIT_COMBAT right after with a Heal event. But not sure if there are other heals (herbing heal) that might trip that.

**Comment by aaronma37** [comment]
Alternatively, could we just add the set of spellids that correspond to drinking the potion (they should be different than the ones that are triggered to make the potion)

**Comment by Dirtimoney** [comment]
> Alternatively, could we just add the set of spellids that correspond to drinking the potion (they should be different than the ones that are triggered to make the potion)

I dont know if they are, i need to craft some health pots on a toon and see

**Comment by Dirtimoney** [comment]
> > Alternatively, could we just add the set of spellids that correspond to drinking the potion (they should be different than the ones that are triggered to make the potion)
> 
> I dont know if they are, i need to craft some health pots on a toon and see

Nevermind they are, clicking the tooltip gives this: spell=441/healing-potion while the creation of the healing potion gives this: spell=3447/healing-potion

Was trying to prevent another list of things to check against
