### ISSUE TITLE
Improve Release developer experience

### ISSUE THREAD

**Issue by blenderer** [Zarant/WoW_Hardcore#223]
We currently have to manually handle a lot of release stuff
Including:

- Zip file for curseforge
- seperate versioning for classic/wotlk
- removing non-dev files from the zip file (curseforge yells at you)
- tagging proper git tags
- creating the release on github

There exist some tools that handle most/all of this and we could easily add these to make this repo easier to work with

**Comment by blenderer** [comment]
The main reason I want to add this in is because frankly, working with this repo is a major pain in the butt. If we make the developer experience more pleasant, we'll be able to develop and release with much less friction!

**Comment by aaronma37** [comment]
Sweet! What are the tools. I agree the release process is a hassle

**Comment by STM3256** [comment]
working on this issue
