### ISSUE TITLE
Self-Made Duo/Trio

### ISSUE THREAD

**Issue by Ballzoffire** [Zarant/WoW_Hardcore#232]
Requesting additional functionality or additional achievement for Duo/Trio Self-made. Did some of my own testing within the LUA files and was able to hardcode in duo names to the self-made check if string.match statement. Unfortunately that is the extent of my abilities with LUA, but I would think that an additional variable that could be called from the duo/trio lua could be used in the self-made. My hackjob example:

```
local function isSelfCreated(...)
    for i = 1, select("#", GameTooltip:GetRegions()) do
        local region = select(i, GameTooltip:GetRegions())
        if region and region:GetObjectType() == "FontString" then
            local text = region:GetText() -- string or nil
            if text ~= nil then
                if string.match(text, player) or string.match(text, duo) or string.match(text, trio) then
                    GameTooltip:Hide() --prevents a hung empty tooltip window
                    return true
                end
            end
        end
    end
    GameTooltip:Hide() --prevents a hung empty tooltip window
    return false
end
```

**Comment by aaronma37** [comment]
Hey just to clarify, this is to be able to equip partner made items when doing selfmade right? Yeah I think your idea works, you can make a PR if you want or I'll try to get to it for the next release

**Comment by Ballzoffire** [comment]
That is exactly my idea for it, Could be a separate achievement so that it doesn't infringe on people who already completed it.

I will try to make the PR but my LUA knowledge/skills are pretty minimal so you will probably beat me to it before I figure it out.
