### ISSUE TITLE
"Low-Intrusion" mode and other sensory adjustments

### ISSUE THREAD

**Issue by zdeyn** [Zarant/WoW_Hardcore#291]
The alert is quite startling and can sometimes covering portions of the screen at the worst time.

Proposal: "Low-Intrusion" customisations, allowing the player to choose:
- Where on screen the alert is positioned
- The size of the alert
- Which sound is played, if any
- .. and so forth

The already-used Ace3 libraries make such configuration via the Interface Options -> AddOns panel straight-forward, and provides excellent groundwork for catering to many groups of special needs and personal tastes without compromising the challenge.

**Comment by aaronma37** [comment]
Position and size exist already. Sound volume would be a nice addition though
