### ISSUE TITLE
MOD bug on 11.11

### ISSUE THREAD

**Issue by STM3256** [Zarant/WoW_Hardcore#312]
ChaosEnd claims to still see buggy behavior with MOD label after initial fix.

>  Still seems to be a bit bugged sometimes i get it, sometimes i dont and others still get it that arn't mods

**Comment by aaronma37** [comment]
@STM3256 Has there been anymore reports? I think this might have resolved itself

**Comment by aaronma37** [comment]
Removed; inactive

**Comment by STM3256** [comment]
@aaronma37 not that I have seen. I guess not an issue :)
