### ISSUE TITLE
Remove kill requirement for achievement quests .. too flaky

### ISSUE THREAD

**Issue by aaronma37** [Zarant/WoW_Hardcore#319]

**Comment by zdeyn** [comment]
I don't think removing the kill requirement is the answer. If we test for 'quest complete' and 'mob killed' and 'below level x' at each event (quest, mob kill, level up) we won't miss any time the objective has been met: complete the quest, kill the mob, all below level x

Jordy has mentioned she'd prefer if some achieves enforced the order more strictly e.g. Benny Blaanco - we want the players to assault the house, not loot an empty one. These types of achieves could be thought of as 'scenarios', and enforce a kill -> quest objective -> quest hand-in below level x order.

A lot of the 'flakiness' can be removed by communicating to the players the precise requirements, and showing some form of in-progress status e.g. quest done (tick), mob killed (tick), good to hand in!

**Comment by aaronma37** [comment]
The flakiness came from kills not being registered all of the time (not necessarily the order).  The strategy was to use parse the chat_xp, but there were cases where the player wasn't awarded xp or that it didnt trigger for whatever reason.  

Another approach could be to use the combat log, but if we do this, we should create a combat log parser for all of the addon because it will be expensive.
