### ISSUE TITLE
Feedback - Winky: "I want it to announce ding level 60 as a big deal"

### ISSUE THREAD

**Issue by zdeyn** [Zarant/WoW_Hardcore#32]
Further, (Tactics) this raises the idea of making it addon-wide, rather than merely guild-wide

**Comment by aaronma37** [comment]
I agree with making addon-wide features. Would help if we want to do inspection/target frames down the line

**Comment by cloudbells** [comment]
Something like this I feel deserves a really unique and special graphic

Other than that, the only thing would be to create a unique message which wouldnt be too hard to do

**Comment by cralor** [comment]
Bump. Should be passing lvl 60 ding out in similar nature to death notifications.

**Comment by aaronma37** [comment]
Added! This is just a guild wide announcement though as of now though.
