### ISSUE TITLE
Ephemeral achievement 'remove repair' buttons bug

### ISSUE THREAD

**Issue by zdeyn** [Zarant/WoW_Hardcore#344]
![image](https://user-images.githubusercontent.com/79044233/220216789-baf6766b-3d38-47d3-b3a6-19bf20c02169.png)
Works as intended on first window load

If you buy something or sell an item to the vendor, however, the buttons get shown.?
![image](https://user-images.githubusercontent.com/79044233/220216840-67bc4ee3-7c0b-4211-9e28-b7b9731dac28.png)

We'll need to either remove the buttons entirely, watch the merchant events to re-hide the buttons, or just block repair the same way we block mailbox and auction house.

**Comment by aaronma37** [comment]
At a glance, I'd guess that re-hiding on merchants updates would be the easiest to do. Removing the button entirely might be the most desirable
