### ISSUE TITLE
Alerts are a little too distracting when playing

### ISSUE THREAD

**Issue by blenderer** [Zarant/WoW_Hardcore#39]
Heard from multiple users:

New alerts are
- too big and center of screen
- raid alert sound is a bit distracting when fighting something

**Comment by zdeyn** [comment]
I recommend an attitude of 'let the player configure the alert features' once we've got the time to implement it properly - Only was quite happy with it, he said it was quite dramatic, but wanted to customize it

**Comment by blenderer** [comment]
Working with Brandung on resizing this so they are less distracting in their default state.
