### ISSUE TITLE
Update minimum alert level description

### ISSUE THREAD

**Issue by isaiahsherfick** [Zarant/WoW_Hardcore#491]
![image](https://github.com/Zarant/WoW_Hardcore/assets/37160728/a3ad1a97-9175-4b9f-9fe9-108d93968c82)
This could be easier to understand -- I did not have any idea what this setting did until I looked at the source code.

**Comment by aaronma37** [comment]
Addon description

**Comment by isaiahsherfick** [comment]
it's fixed in my still open PR 
https://github.com/Zarant/WoW_Hardcore/pull/490
