### ISSUE TITLE
alert custom message - grief 

### ISSUE THREAD

**Issue by 1010101110** [Zarant/WoW_Hardcore#60]
someone sending custom alerts

https://clips.twitch.tv/UninterestedCautiousDadGOWSkull-NCmEbumI7cwqOqyZ

https://clips.twitch.tv/SparklyPlausibleSoymilkHotPokket-BwwbPRl73-aZIBlJ

**Comment by 1010101110** [comment]
remove the debug command prob https://github.com/Zarant/WoW_Hardcore/blob/master/Hardcore.lua#L251-L270

**Comment by 1010101110** [comment]
so they were using this https://github.com/Zarant/WoW_Hardcore/blob/299f787d171f579a11b0bc705d17ab34f51b3d6e/Hardcore.lua#L502

**Comment by RobertB4** [comment]
they sent their custom message in the "name" field

**Comment by blenderer** [comment]
I suppose we send the guid of the player instead of the name

**Comment by RobertB4** [comment]
is there a way to convert the guid to the character name though?

**Comment by aaronma37** [comment]
We have the sender name via ctl right?

**Comment by aaronma37** [comment]
Additionally we should print sender name with debug on; if someone is trolling we can have a mod turn it on and find how who it is

**Comment by blenderer** [comment]
I'm working on this now

**Comment by RobertB4** [comment]
https://github.com/Zarant/WoW_Hardcore/pull/64/files
