### ISSUE TITLE
Spam death alerts griefing

### ISSUE THREAD

**Issue by blenderer** [Zarant/WoW_Hardcore#62]
Currently, it is possible for an attacker to send rapid spam death alerts to everyone in the guild. Simply by changing their local lua code

To fix this, we need to detect the last death sent by the sender and store a timestamp somewhere. If the last death alert from the sender was less than 3~ minutes ago, we can safely ignore the death.

We also can add a Hardcore:Debug() log of who is sending the death alert. This will help admins and mods remove the offender

**Comment by aaronma37** [comment]
#63
