### ISSUE TITLE
Gap between played time and addon uptime

### ISSUE THREAD

**Issue by ghost** [Zarant/WoW_Hardcore#69]
After taking a short break and logging back to the game I was welcomed with this error message saying that my played time is different than addon uptime, even though I had it since I started and never turned it off. The gap is literally my whole /played time and I can't figuer out what caused it or how to fix it. I have the log of my levels in the hardcore addon, so If I really had the addon off, it wouldn't track the level ups I guess ? Thanks for any info, Simon (Eluff)

https://imgur.com/a/2OIOya7

Verification hash string:
80ad108ZX97nn121Osm101dxT114xX45HkQ53ED50EM50cY51sp45Lt48hK49dw50Nxd70SQ66ZXh69Tj67Tg49GbS_81icG117VX101krJ108QOu39tP83ys101gFX114kU114MX97nTs114Uds_68Ya119swS97EW114tYq102JS_72DO85QR78LW84BS69lMP82hp_69yv108PR117Zx102yf102OLI_56XOB_55Iny53NIW48SY55Vi_50vw50Wb53xb_48ZLa___49dl49QBk47uG49Dr55rD47aRm50Mf49bK32cp49rZc48U58ZwN53aG50ZG58Qdc52Me48jmf%55Ob51bd50kM55NIj

**Comment by simon-prokopec** [comment]
Character info really seems to be broken for me, the object with saved data looks like this:


Hardcore_Character = {
	["accumulated_time_diff"] = 8258,
	["grief_warning_conditions"] = 3,
	["guid"] = "Player-5223-012FBEC1",
	["time_tracked"] = 261,
	["time_played"] = 8519,
	["trade_partners"] = {
	},
	["played_time_gap_warnings"] = {
		{
			["date"] = "11/17/21 11:48:54",
			["duration_since_last_recording"] = 8280,
		}, -- [1]
	},
	["bubble_hearth_incidents"] = {
	},
	["deaths"] = {
	},
	["tracked_played_percentage"] = 0,
}

Should I just make a new character ? If so, how should I prevent this from happening again ? I'm playing on 1 PC only

**Comment by 1010101110** [comment]
addressed in #59
